spring:
  application:
    name: address-service-local
  datasource:
    driver-class-name: org.postgresql.Driver
    username: example
    password: 123456
    url: jdbc:postgresql://localhost:5432/addressdb
    platform: postgres
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql
  cloud:
    stream:
      bindings:
        output:
          destination: addressChangeTopic
          content-type: application/json
        kafka:
         binder:
          zkNodes: localhost
          brokers: localhost

server:
  port: 4568
  tomcat:
    max-threads: 5
